update ci (#1)
* update ci

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,28 +1,29 @@
 name: Build code-server image
-run-name: >-
-  Build
-  ${{ github.event_name == 'workflow_dispatch' && 'beta-' || '' }}
-  ${{ github.event.inputs.version || github.ref_name }}
+run-name: Build ${{ github.event.inputs.version || github.ref_name }}
 
 on:
-  push:
-    tags:
-      - "v*.*.*"
-
   workflow_dispatch:
     inputs:
-      version:
-        description: "Image version (e.g. v0.0.1)"
-        required: true
-        type: string
+      VERSION:
+        description: "Upstream code-server version (e.g. 0.0.1)"
+        required: false
+
+  pull_request:
+    branches:
+      - 'main'
+
+  schedule:
+    - cron: "30 2 * * *"
 
 permissions:
   contents: read
   packages: write
 
 env:
+  PUB_IMAGE: archie2016/code-server
   IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/code-server
   ACR_IMAGE: ${{ secrets.ACR_MY_REGISTY }}/osc-org/code-server
+  QCR_IMAGE: ${{ secrets.QCR_REGISTRY }}/osc-org/code-server
 
 jobs:
   build:
@@ -32,40 +33,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v6
 
-      # ------------------------------------------------
-      # 校验并获取当前镜像版本
-      # ------------------------------------------------
-      - name: Resolve image version
-        shell: bash
-        run: |
-          set -euo pipefail
-
-          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
-            RAW_VERSION="${{ inputs.version }}"
-            VERSION="beta-${RAW_VERSION}"
-          else
-            RAW_VERSION="${GITHUB_REF_NAME}"
-            VERSION="${RAW_VERSION}"
-          fi
-
-          # 校验原始格式
-          if ! [[ "$RAW_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format: $RAW_VERSION"
-            echo "Expected format: v0.0.1"
-            exit 1
-          fi
-
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-
-          echo "Image version: ${VERSION}"
-
-      # ------------------------------------------------
-      # 安装 skopeo
-      # ------------------------------------------------
-      - name: Install skopeo
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y skopeo jq
 
       # ------------------------------------------------
       # 获取最新 upstream version-* tag
@@ -92,21 +59,62 @@ jobs:
 
           echo "Upstream version: ${BASE_VERSION}"
 
+      - name: Resolve image version
+        shell: bash
+        run: |
+          set -euo pipefail
+          set -x
+          VERSION=
+          if [[ ${GITHUB_EVENT_NAME} == workflow_dispatch ]] && [[ -n "${{ inputs.version }}" ]]; then
+            VERSION="${{ inputs.version }}"
+            EXIST=$(skopeo list-tags docker://docker.io/linuxserver/code-server \
+              | jq -r '.Tags[]' \
+              | grep -E '^version-[0-9]+(\.[0-9]+){2}' \
+              | grep '^version-'${VERSION}'$')
+            if [[ -z "${EXIST}" ]]; then
+              echo "code-server version not found"
+              exit 1
+            fi
+          else
+            VERSION=${BASE_VERSION#version-}
+          fi
+
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
+          echo "Image version: ${VERSION}"
+
+      - name: Login to Docker Hub
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v4
+        with:
+          username: archie2016
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
       # 登录 GitHub Container Registry
       - name: Login to GHCR
+        if: github.event_name != 'pull_request'
         uses: docker/login-action@v4
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
-          password: ${{ secrets.AGH_TOKEN }}
+          password: ${{ secrets.GH_TOKEN }}
 
       # 登录 ACR Container Registry
       - name: Login to ACR
+        if: github.event_name != 'pull_request'
         uses: docker/login-action@v4
         with:
-          registry: ${{ secrets.ACR_MY_REGISTY }}
-          username: ${{ secrets.ACR_MY_USER }}
-          password: ${{ secrets.ACR_MY_PASS }}
+          registry: ${{ secrets.ACR_REGISTY }}
+          username: ${{ secrets.ACR_USER }}
+          password: ${{ secrets.ACR_PASS }}
+
+      - name: Log in to QCR Registry
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ secrets.QCR_REGISTRY }}
+          username: ${{ secrets.QCR_USER }}
+          password: ${{ secrets.QCR_PASS }}
 
       # ------------------------------------------------
       # Buildx
@@ -122,13 +130,17 @@ jobs:
         with:
           context: .
           file: ./Dockerfile
-          push: true
+          push: ${{ github.event_name != 'pull_request' }}
           platforms: linux/amd64,linux/arm64
           tags: |
             ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
             ${{ env.IMAGE_NAME }}:latest
             ${{ env.ACR_IMAGE }}:${{ env.VERSION }}
             ${{ env.ACR_IMAGE }}:latest
+            ${{ env.QCR_IMAGE }}:${{ env.VERSION }}
+            ${{ env.QCR_IMAGE }}:latest
+            ${{ env.PUB_IMAGE }}:${{ env.VERSION }}
+            ${{ env.PUB_IMAGE }}:latest
           build-args: |
             BASE_VERSION=${{ env.BASE_VERSION }}
           cache-from: type=gha
