2

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,20 +5,18 @@ run-name: >-
   ${{ github.event.inputs.version || github.ref_name }}
 
 on:
-  push:
-    tags:
-      - "v*.*.*"
-
   workflow_dispatch:
     inputs:
-      version:
-        description: "Image version (e.g. v0.0.1)"
-        required: true
-        type: string
-  
+      VERSION:
+        description: "Upstream code-server version (e.g. 0.0.1)"
+        required: false
+
   pull_request:
     branches:
       - 'main'
+
+  schedule:
+    - cron: "30 2 * * *"
 
 permissions:
   contents: read
@@ -68,23 +66,23 @@ jobs:
         shell: bash
         run: |
           set -euo pipefail
-
-          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
-            RAW_VERSION="${{ inputs.version }}"
-            VERSION="beta-${RAW_VERSION}"
+          set -x
+          VERSION=
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]] && [[ -n "${{ inputs.version }}" ]]; then
+            VERSION="${{ inputs.version }}"
+            EXIST=$(skopeo list-tags docker://docker.io/linuxserver/code-server \
+              | jq -r '.Tags[]' \
+              | grep -E '^version-[0-9]+(\.[0-9]+){2}' \
+              | grep '^version-'${VERSION}'$')
+            if [[ -z "${EXIST}" ]]; then
+              echo "code-server version not found"
+              exit 1
+            fi
           else
-            RAW_VERSION="${GITHUB_REF_NAME}"
-            VERSION="${RAW_VERSION}"
+            VERSION=${BASE_VERSION#version-}
           fi
 
-          # 校验原始格式
-          if ! [[ "$RAW_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format: $RAW_VERSION"
-            echo "Expected format: v0.0.1"
-            exit 1
-          fi
-
-          echo "VERSION=${BASE_VERSION#version-}" >> $GITHUB_ENV
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
           echo "Image version: ${VERSION}"
 
